[versions]

# Compose
# https://developer.android.com/jetpack/androidx/releases/compose.
compose = "1.2.0-beta01"
composeMaterial3 = "1.0.0-alpha11"

# Kotlin
# https://kotlinlang.org/docs/releases.html#release-details.
kotlin = "1.6.21"
coroutines = "1.6.0"
datetime = "0.3.3"

[plugins]

agp = { id = "com.android.application", version = "7.1.3" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
apolloKotlin = { id = "com.apollographql.apollo3", version = "3.2.2" }
hilt = { id = "com.google.dagger.hilt.android", version = "2.41" }

[libraries]

# AndroidX
# TODO: Update and "bundle" dependencies.
androidx-activityCompose = "androidx.activity:activity-compose:1.4.0"
androidx-coreKtx = "androidx.core:core-ktx:1.7.0"
androidx-lifecycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.1"
androidx-navigationCompose = "androidx.navigation:navigation-compose:2.4.1"
androidx-test-junit = "androidx.test.ext:junit:1.1.3"
androidx-test-espressoCore = "androidx.test.espresso:espresso-core:3.4.0"

# Compose
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-toolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-test-ui-testJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
compose-test-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }

# Apollo Kotlin
apolloKotlin-runtime = "com.apollographql.apollo3:apollo-runtime:3.2.2"

# COIL
coil-compose = "io.coil-kt:coil-compose:2.0.0-rc01"

# Kotlin
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }

# Hilt
# TODO: Update and "bundle" dependencies.
hilt-android = "com.google.dagger:hilt-android:2.41"
hilt-android-compiler = "com.google.dagger:hilt-android-compiler:2.41"
hilt-navigationCompose = "androidx.hilt:hilt-navigation-compose:1.0.0"

# Accompanist
accompanist-systemUiController = "com.google.accompanist:accompanist-systemuicontroller:0.24.7-alpha"

# Test
test-junit = "junit:junit:4.13.2"
