[libraries]

# TODO:
#  Use the versions.ref API where appropriate; see:
#  https://github.com/chrisbanes/tivi/blob/main/gradle/libs.versions.toml

# AndroidX
androidx-activityCompose = "androidx.activity:activity-compose:1.4.0"
androidx-coreKtx = "androidx.core:core-ktx:1.7.0"
androidx-lifecycle-runtimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.1"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.4.1"

androidx-test-junit = "androidx.test.ext:junit:1.1.3"
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.4.0"


# Compose
compose-foundation = "androidx.compose.foundation:foundation:1.2.0-alpha08"
compose-material = "androidx.compose.material:material:1.1.1"
compose-material3 = "androidx.compose.material3:material3:1.0.0-alpha07"
compose-runtime = "androidx.compose.runtime:runtime:1.2.0-alpha05"
compose-ui = "androidx.compose.ui:ui:1.1.1"
compose-uiToolingPreview = "androidx.compose.ui:ui-tooling-preview:1.1.1"

compose-test-uiTestJunit4 = "androidx.compose.ui:ui-test-junit4:1.1.1"
compose-test-uiTooling = "androidx.compose.ui:ui-tooling:1.1.1"

# Apollo Kotlin
apolloKotlin-runtime = "com.apollographql.apollo3:apollo-runtime:3.2.2"

# COIL
coil-compose = "io.coil-kt:coil-compose:2.0.0-rc01"

# Kotlin
kotlin-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.0"
kotlin-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0"
kotlin-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.3.2"

# Hilt
hilt-android = "com.google.dagger:hilt-android:2.41"
hilt-android-compiler = "com.google.dagger:hilt-android-compiler:2.41"
hilt-navigationCompose = "androidx.hilt:hilt-navigation-compose:1.0.0"

# Accompanist
accompanist-systemUiController = "com.google.accompanist:accompanist-systemuicontroller:0.24.7-alpha"

# Test
test-junit = "junit:junit:4.13.2"
