# This workflow notifies Discord when a release is created
name: notify-build-debug-complete

on:
  release:
    types: [published]

jobs:
  on-complete:
    runs-on: ubuntu-latest
    steps:
      - name: Notify workflow completed
        uses: sarisia/actions-status-discord@v1
        env:
          DISCORD_WEBHOOK: ${{ secrets.RELEASES_WEBHOOK }}
